"""Fill the metrics block in README.md from the report files.

Usage:
    python -m credit_risk.sync_readme            rewrite the block
    python -m credit_risk.sync_readme --check    exit 1 when the block would change

README.md holds one block between <!-- metrics:start --> and <!-- metrics:end -->. The block is
rendered from reports/metrics.json, reports/loadtest.json, reports/fairness.json, and
models/version.json. A missing file renders [todo] for every field it would have filled, so no
number is ever typed by hand. Running the command twice changes nothing.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from credit_risk import settings

START = "<!-- metrics:start -->"
END = "<!-- metrics:end -->"
TODO = "[todo]"
GENERATED_NOTE = (
    "<!-- Generated by python -m credit_risk.sync_readme from reports/*.json and "
    "models/version.json. Edit those files, not this block. -->"
)
SHA_SHORT_LENGTH = 12
COMMAND = "python -m credit_risk.sync_readme"

SOURCES: dict[str, str] = {
    "metrics": "reports/metrics.json",
    "loadtest": "reports/loadtest.json",
    "fairness": "reports/fairness.json",
    "version": "models/version.json",
}


# ---------------------------------------------------------------------------
# Receipts
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Receipts:
    """The four source documents; any of them may be None when its file is absent."""

    metrics: dict | None
    loadtest: dict | None
    fairness: dict | None
    version: dict | None

    def get(self, source: str, *keys: str) -> Any:
        """Walk nested keys; None when the source or any key is missing."""
        node: Any = getattr(self, source)
        for key in keys:
            if not isinstance(node, dict) or key not in node:
                return None
            node = node[key]
        return node

    def missing(self) -> list[str]:
        return [path for name, path in SOURCES.items() if getattr(self, name) is None]


def read_json_optional(path: Path) -> dict | None:
    if not path.is_file():
        return None
    with open(path, encoding="utf-8") as fh:
        doc = json.load(fh)
    return doc if isinstance(doc, dict) else None


def load_receipts(root: Path) -> Receipts:
    return Receipts(
        metrics=read_json_optional(root / SOURCES["metrics"]),
        loadtest=read_json_optional(root / SOURCES["loadtest"]),
        fairness=read_json_optional(root / SOURCES["fairness"]),
        version=read_json_optional(root / SOURCES["version"]),
    )


# ---------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------


def is_number(value: Any) -> bool:
    return isinstance(value, int | float) and not isinstance(value, bool)


def f4(value: Any) -> str:
    """Metrics: four decimals."""
    return f"{value:.4f}" if is_number(value) else TODO


def f3(value: Any) -> str:
    """Thresholds: three decimals."""
    return f"{value:.3f}" if is_number(value) else TODO


def f2(value: Any) -> str:
    """Latency in milliseconds and targets: two decimals."""
    return f"{value:.2f}" if is_number(value) else TODO


def fint(value: Any) -> str:
    """Counts: integers with thousands separators."""
    return f"{int(value):,}" if is_number(value) else TODO


def ftext(value: Any) -> str:
    return str(value) if isinstance(value, str) and value else TODO


def fshort(value: Any, length: int = SHA_SHORT_LENGTH) -> str:
    return value[:length] if isinstance(value, str) and value else TODO


def cost_ratio(receipts: Receipts) -> str:
    """The cost matrix as 'false negative : false positive', for example 5:1."""
    fn = receipts.get("metrics", "threshold_selection", "cost_false_negative")
    fp = receipts.get("metrics", "threshold_selection", "cost_false_positive")
    if is_number(fn) and is_number(fp):
        return f"{fn:g}:{fp:g}"
    return TODO


def model_label(receipts: Receipts) -> str:
    model = receipts.get("version", "model")
    if model == "hgb":
        return "HGB"
    return ftext(model)


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------


def render_readme(r: Receipts) -> str:
    """Metrics table, threshold policy table, then latency, fairness, and provenance lines."""
    base = ("metrics", "baseline_logreg")
    at = ("metrics", "at_threshold")
    at_pt = ("metrics", "at_precision_target")
    lines = [
        GENERATED_NOTE,
        f"Held-out test split, n = {fint(r.get('metrics', 'n_test'))}, positive rate "
        f"{f4(r.get('metrics', 'positive_rate_test'))}. Nothing below was tuned on it.",
        "",
        f"| Metric | {model_label(r)} (this model) | Logistic baseline |",
        "|---|---|---|",
        f"| ROC-AUC | {f4(r.get('metrics', 'roc_auc'))} | {f4(r.get(*base, 'roc_auc'))} |",
        f"| PR-AUC (average precision) | {f4(r.get('metrics', 'pr_auc'))} | "
        f"{f4(r.get(*base, 'pr_auc'))} |",
        f"| Brier score (lower is better) | {f4(r.get('metrics', 'brier'))} | "
        f"{f4(r.get(*base, 'brier'))} |",
        f"| KS statistic | {f4(r.get('metrics', 'ks'))} | {f4(r.get(*base, 'ks'))} |",
        "",
        "Threshold policy, chosen on the validation split and then applied unchanged to test:",
        "",
        "| Policy | Threshold | Precision | Recall | Selection rate |",
        "|---|---|---|---|---|",
        f"| Cost-optimal, the API default ({cost_ratio(r)} cost matrix, illustrative) | "
        f"{f3(r.get('metrics', 'threshold_cost_optimal'))} | {f4(r.get(*at, 'precision'))} | "
        f"{f4(r.get(*at, 'recall'))} | {f4(r.get(*at, 'selection_rate'))} |",
        f"| Precision target {f2(r.get('metrics', 'threshold_selection', 'target_precision'))} | "
        f"{f3(r.get('metrics', 'threshold_precision_target'))} | "
        f"{f4(r.get(*at_pt, 'precision'))} | {f4(r.get(*at_pt, 'recall'))} | "
        f"{f4(r.get(*at_pt, 'selection_rate'))} |",
        "",
        f"Latency: p95 {f2(r.get('loadtest', 'p95_ms'))} ms for POST /predict, "
        f"{fint(r.get('loadtest', 'requests'))} requests at concurrency "
        f"{fint(r.get('loadtest', 'concurrency'))}, on {ftext(r.get('loadtest', 'host'))} "
        "(reports/loadtest.json).",
        "",
        "Fairness at the cost-optimal threshold, from held-out labels: demographic parity ratio "
        f"{f4(r.get('fairness', 'sex', 'demographic_parity_ratio'))} by sex and "
        f"{f4(r.get('fairness', 'age_band', 'demographic_parity_ratio'))} by age band "
        "(reports/fairness.json).",
        "",
        f"Provenance: trained {ftext(r.get('version', 'trained_at'))}, git "
        f"{ftext(r.get('version', 'git_sha_short'))}, data sha256 "
        f"{fshort(r.get('version', 'data_sha256'))}, rows {fint(r.get('metrics', 'n_train'))} "
        f"train / {fint(r.get('metrics', 'n_val'))} validation / "
        f"{fint(r.get('metrics', 'n_test'))} test (models/version.json).",
    ]
    return "\n".join(lines)


TARGETS: dict[str, Callable[[Receipts], str]] = {
    "README.md": render_readme,
}


# ---------------------------------------------------------------------------
# Block replacement
# ---------------------------------------------------------------------------


def replace_block(text: str, block: str) -> str:
    """Swap the content between the markers; the markers themselves stay on their own lines."""
    if text.count(START) != 1 or text.count(END) != 1:
        raise ValueError(f"expected exactly one {START} and one {END}")
    start = text.index(START) + len(START)
    end = text.index(END)
    if end < start:
        raise ValueError(f"{END} appears before {START}")
    return f"{text[:start]}\n{block}\n{text[end:]}"


def sync(
    root: Path,
    check: bool,
    targets: dict[str, Callable[[Receipts], str]] | None = None,
    command: str = COMMAND,
) -> int:
    """Rewrite (or, with check, only compare) every target. Returns the exit code.

    ``targets`` maps a path relative to ``root`` to the function that renders its block;
    ``command`` names the command a stale file should be fixed with.
    """
    receipts = load_receipts(root)
    for path in receipts.missing():
        print(f"note: {path} is missing; its fields render as {TODO}")

    stale: list[str] = []
    for relative, render in (targets or TARGETS).items():
        path = root / relative
        if not path.is_file():
            print(f"note: {relative} is absent here; skipped")
            continue
        raw = path.read_bytes().decode("utf-8")
        try:
            updated = replace_block(raw.replace("\r\n", "\n"), render(receipts))
        except ValueError as exc:
            print(f"error: {relative}: {exc}", file=sys.stderr)
            return 2
        if updated == raw:
            print(f"unchanged  {relative}")
            continue
        stale.append(relative)
        if check:
            print(f"stale      {relative}")
        else:
            path.write_bytes(updated.encode("utf-8"))
            print(f"updated    {relative}")

    if check and stale:
        print(f"{len(stale)} file(s) would change; run {command}", file=sys.stderr)
        return 1
    return 0


def build_parser(prog: str, description: str) -> argparse.ArgumentParser:
    """The shared command line: --check and --root."""
    parser = argparse.ArgumentParser(prog=prog, description=description)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the block differs from what the reports render, write nothing",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=settings.REPO_ROOT,
        help="repository root (default: the folder holding params.yaml)",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser(
        prog=COMMAND,
        description="Fill the metrics block in README.md from the reports.",
    )
    args = parser.parse_args(argv)
    return sync(args.root.resolve(), args.check)


if __name__ == "__main__":
    sys.exit(main())
